import type { OrderRecord } from '../../lib/orders'

export const MOCK_ORDERS: OrderRecord[] = [
  {
    id: 'sample-101',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    customer_name: 'Angela Villanueva',
    pronouns: 'she/her',
    email: 'angela.v@gmail.com',
    social_link: '@angela.reads',
    phone: '09171234567',
    address: 'Unit 402, Solstice Tower, Circuit Makati, Carmona, Makati City, Metro Manila 1207',
    shipping_method: 'jt_manila',
    package_type: 'personalized',
    freebie_photocard: 'Design 1A (Sunset Flowers)',
    additional_photocards: 'Design 2B (Coffee & Pages)',
    postcard_message: 'How do you practice giving yourself grace during days when everything feels overwhelming?',
    total_amount: 784,
    receipt_url: '/images/payments/gcash.jpg',
    status: 'pending',
  },
  {
    id: 'sample-102',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    customer_name: 'Bea Mae Soriano',
    pronouns: 'she/her',
    email: 'beamae@yahoo.com',
    social_link: '@beamae.s',
    phone: '09289876543',
    address: 'Block 12 Lot 5, Camella Homes, Barangay San Isidro, Antipolo City, Rizal 1870',
    shipping_method: 'jt_luzon',
    package_type: 'standard',
    freebie_photocard: null,
    additional_photocards: null,
    postcard_message: null,
    total_amount: 735,
    receipt_url: '/images/payments/maya.jpg',
    status: 'confirmed',
  },
  {
    id: 'sample-103',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    customer_name: 'Carlos Miguel Reyes',
    pronouns: 'he/him',
    email: 'carlos.reyes@outlook.com',
    social_link: '@carlos.reads',
    phone: '09085551234',
    address: '15 Rosal St., Guadalupe Nuevo, Makati City, Metro Manila',
    shipping_method: 'lalamove',
    package_type: 'personalized',
    freebie_photocard: 'Design 3A (Cloud Reflection)',
    additional_photocards: null,
    postcard_message: 'A reminder about not rushing into the future and trusting my current pace in life.',
    total_amount: 699,
    receipt_url: '/images/payments/land.jpg',
    status: 'shipped',
  },
]
